### ISSUE TITLE
可能是个 bug

### ISSUE THREAD

**Issue by jalenzz** [jinqimu/AddPhotoFrame#1]
处理完一张图片只后，对输出的图片（图一）再次进行处理，此时输出的图（图二）就有点小问题了，没有自动加上那个东西
![53e093a5ffaf4f45790741eae7378a36_2_3_art_sol](https://user-images.githubusercontent.com/57910033/87934573-e7856780-cac1-11ea-89ac-91f775182fa1.png)
![53e093a5ffaf4f45790741eae7378a36_2_3_art_sol_sol](https://user-images.githubusercontent.com/57910033/87934575-e81dfe00-cac1-11ea-9f74-4b75928942ed.png)

还有，想问下 小图标下方的 `PENTAXK-70` 是需要什么设置才能有吗:bow:

**Comment by jinqimu** [comment]
* **AddPhotoFrame**更适用于含有exif信息的图片
* 未复现你的问题👇![](https://cdn.jsdelivr.net/gh/jinqimu/cloudimg/img/20200720202107.png)
  可能是由于你使用了release中的EXE文件，那么你可以选择1、运行`main.py`/`APF.html`(lighter) 2、等我发布release（上次忘release了，淦

P.S. `PENTAXK-70`是我的破相机型号，同理小红标是相机品牌

**Comment by jalenzz** [comment]
好吧，谢谢啦

不知道能不能自定义图标和文字（如果没获取到信息，也没有自定义的情况下就采用默认），手机拍的都没有 exif 信息 :cry: 但真的很好看啊

**Comment by jinqimu** [comment]
* 其他厂商图标将在可见的未来受到支持😎
* 手机应该是有exif的，可能是你没开，如果对设计有什么建议可以另开issue或草图发到我邮箱
* 手机上建议可以直接使用👉[APF_DEMO](https://jinqimu.xyz/apf/)

**Comment by jalenzz** [comment]
:+1:
嗯，谢谢，之前直接拿电脑上的图片试了，刚刚用手机图片，发现是可以的
但，显示好像有点小问题
![15952502413426272774722476088975](https://user-images.githubusercontent.com/57910033/87940947-f02f6b00-cacc-11ea-966c-b041c9560d84.jpg)

（顺便，相机型号下面那行是什么信息呀）

**Comment by jinqimu** [comment]
* 关于**S** 和 **EV** 的bug，请发送带有exif信息的原图到我的邮箱（各家的exif可能有些许不同）
* 相机型号下面是镜头型号

P.S. 设计之初按相机常用的3:2，手机常用4:3/16:9，你可以看到图片与logo十分贴近，未来会fix

**Comment by jalenzz** [comment]
嗯，已发至邮箱。期待越来越好
